//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cariler
    {
        public int Id { get; set; }
        public string CariKodu { get; set; }
        public string CariAdi { get; set; }
        public string CariGrupAdi { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string CariGrupKodu { get; set; }
        public Nullable<int> GrupId { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string CepTelefon { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public string WebAdres { get; set; }
        public string Yetkili { get; set; }
        public string YetkiliMail { get; set; }
        public Nullable<System.DateTime> TarihKaydet { get; set; }
        public string Kullanici { get; set; }
        public Nullable<System.DateTime> DuzenlemeTarihi { get; set; }
        public string KullaniciDuzenle { get; set; }
    }
}
