//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariGrup
    {
        public int Id { get; set; }
        public string GrupAdi { get; set; }
        public string GrupKodu { get; set; }
        public string KullaniciKayit { get; set; }
        public Nullable<System.DateTime> TarihDuzenle { get; set; }
        public string KullaniciDuzenle { get; set; }
        public Nullable<System.DateTime> TarihKaydet { get; set; }
    }
}
