//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teklifler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teklifler()
        {
            this.TeklifKalemler = new HashSet<TeklifKalemler>();
        }
    
        public int Id { get; set; }
        public byte Tip { get; set; }
        public string EvrakNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string CariAdi { get; set; }
        public string Yetkili { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Not { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<decimal> IskontoToplam { get; set; }
        public Nullable<decimal> KdvToplam { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public string Kullanici { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifKalemler> TeklifKalemler { get; set; }
    }
}
