//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeklifKalemler
    {
        public int Id { get; set; }
        public int TeklifId { get; set; }
        public string Barkod { get; set; }
        public string UrunAdi { get; set; }
        public string Birim { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<decimal> IskontoOran { get; set; }
        public Nullable<int> KdvOran { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<decimal> KdvTutar { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
    
        public virtual Teklifler Teklifler { get; set; }
    }
}
