//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeknikServis
    {
        public int Id { get; set; }
        public string SeriNo { get; set; }
        public string Barkod { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public string TeslimAlan { get; set; }
        public string UrunGrubu { get; set; }
        public string Aciklama { get; set; }
        public string MusteriBeyani { get; set; }
        public string UzerindeGelenler { get; set; }
        public string Durumu { get; set; }
    }
}
